### ISSUE TITLE
As of API 29 Environment.getExternalStorageDirectory() is deprecated.

### ISSUE THREAD

**Issue by shrine2000** [hendrawd/StorageUtil#3]
https://github.com/hendrawd/StorageUtil/blob/514bca5404e2a302c5f490a07a9c72fe08b04fca/library/src/main/java/hendrawd/storageutil/library/StorageUtil.java#L123

**Comment by mi234** [comment]
Thank you I've never done this before so I'm having a hard time lol

**Comment by hendrawd** [comment]
Yes, it is deprecated on API 29 because of the user's privacy concern. Please use the recommended ways such as:
Context#getExternalFilesDir(String), MediaStore, or Intent#ACTION_OPEN_DOCUMENT.
