### ISSUE TITLE
Can't use it!

### ISSUE THREAD

**Issue by Yangqingchun** [hendrawd/StorageUtil#6]
![image](https://user-images.githubusercontent.com/33993115/146316642-7d397d7d-42cb-4fcb-873a-6b519bdedd53.png)
![image](https://user-images.githubusercontent.com/33993115/146316678-0d09dd13-534a-4f1d-a392-aee54d594274.png)

**Comment by hendrawd** [comment]
@Yangqingchun Hi, sorry for the late response. For the new gradle configuration, you can open your `settings.gradle`, then add `maven { url 'https://jitpack.io' }` inside `dependencyResolutionManagement` -> `repositories`. Hope this helps. Let me know if you have more problems.
```groovy
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter() // Warning: this repository is going to shut down soon
        maven { url 'https://jitpack.io' } // <--- add this
    }
}
```

**Comment by hendrawd** [comment]
Just configuration issue, not library issue.
